---
- name: Install base packages
  hosts: all
  become: true
  tasks:
    - name: Update the package cache
      ansible.builtin.apt:
        update_cache: true
 
    - name: Install base packages
      ansible.builtin.apt:
        name:
          - openssh-server
          - git
          - build-essential
          - htop
        state: present
 