---
# This role contains common tasks to run on all (RHEL) nodes
- name: Install EPEL
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install base packages
  ansible.builtin.dnf:
    update_cache: true
    name:
      - openssh-server
      - git
      - htop
    state: present
