---
# This role contains common tasks to run on all (debian) nodes
- name: Install base packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - openssh-server
      - git
      - htop
      - curl
      - wget
    state: present
